# Generated by Django 4.2.9 on 2026-04-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('electronics', 'Eletrônicos'), ('clothing', 'Vestuário'), ('books', 'Livros'), ('home', 'Casa & Jardim'), ('sports', 'Esportes'), ('beauty', 'Beleza & Saúde'), ('toys', 'Brinquedos'), ('food', 'Alimentos'), ('other', 'Outros')], default='other', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('min_stock_alert', models.PositiveIntegerField(default=5, help_text='Alerta quando estoque ficar abaixo deste valor')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
